# See https://github.com/apache/infrastructure-asfyaml for .asf.yaml docs

github:
  features:
    issues: false
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: cvs@httpd.apache.org
  issues: bugs@httpd.apache.org
  pullrequests: cvs@httpd.apache.org

pelican:
  notify: dev@httpd.apache.org
  autobuild: preview/*
  target: asf-site
  theme: theme/apache
  whoami: main

staging:
  profile:
  whoami: asf-site
  autostage: preview/*

publish:
  whoami: asf-site
