name: Build a Pelican Website
on:
  push:
    # This prevents the workflow from running automatically on a new branch
    # When creating a new site branch, please ensure that the push and checkout branches agree
    # and that the action/pelican destination value is updated accordingly
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This must equal the push/branches list above, and be appropriate for the destination below
          ref: 'main'
      - uses: apache/infrastructure-actions/pelican@main
        with:
          # This must be appropriate for the branch being built
          # destination: 'asf-site'
          destination: 'preview/covener-test'
          publish: true
          gfm: 'true'
